@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits MediBook])
    :Purge redunant states;
    :Save MediBook to
    mediBookStateList;
else ([else])
endif
stop
@enduml
