@startuml
start
:User executes create account command;
:Logic executes the string input;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([user details are of an acceptable format])
    :CreateAccountCommand is created;
    :Logic calls Storage to save the user details;
else ([incorrect format])
    :Logic throws a parse error;
endif
stop
@enduml
