@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyMediBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class MediBook
Class ReadOnlyMediBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Patient {
Class Patient
Class IC
Class DateOfBirth
Class Height
Class Weight
Class Bmi
Class BloodType
Class Address
Class Email
Class Phone
Class Record
Class UniquePatientList
}

Package CommonFields {
Class Date
Class Name
}

Package MedicalDetail {
Class Tag
Class Allergy
Class Condition
Class Treatment
}

Package MedicalNote {
Class MedicalNoteList
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

MediBook .up.|> ReadOnlyMediBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" MediBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Allergy -down-|> Tag
Condition -down-|> Tag
Treatment -down-|> Tag

MediBook *--> "1" UniquePatientList
UniquePatientList o--> "*" Patient
Patient *--> "1" IC
Patient *--> "1" DateOfBirth
Patient *--> "1" Name
Patient *--> "1" Phone
Patient *--> "0..1" Email
Patient *--> "0..1" Address
Patient *--> "0..1" Height
Patient *--> "0..1" Weight
Patient *--> "0..1" BloodType
Patient *--> "0..1" Bmi
Patient *--> "*" Allergy
Patient *--> "*" Condition
Patient *--> "*" Treatment
Patient *--> "1" MedicalNoteList
Patient *--> "1" Record
Bmi --> Height
Bmi --> Weight

DateOfBirth *--> Date

DateOfBirth -[hidden]down-> Date
Date -[hidden]right-> Name

IC -[hidden]right-> Name
DateOfBirth -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Bmi -[hidden]down-> Height
Bmi -[hidden]down-> Weight
Tag -[hidden]down-> MedicalNoteList


ModelManager -->"1" Patient : filtered list
@enduml
