@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MediBookParser" as MediBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedMediBook" as VersionedMediBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> MediBookParser : parseCommand(undo)
activate MediBookParser

create UndoCommand
MediBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> MediBookParser
deactivate UndoCommand

MediBookParser --> LogicManager : u
deactivate MediBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoMediBook()
activate Model

Model -> VersionedMediBook : undo()
activate VersionedMediBook

VersionedMediBook -> VersionedMediBook :resetData(ReadOnlyMediBook)
VersionedMediBook --> Model :
deactivate VersionedMediBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
